apiVersion: v2
name: encryption-provider-operator
version: 0.7.0-dev
description: "Operator for managing encryption config for encrypting k8s secrets in etcd"
appVersion: 0.7.0-dev
home: "https://github.com/giantswarm/encryption-provider-operator"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  config.giantswarm.io/version: 1.x.x
  io.giantswarm.application.team: phoenix
